# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: NOAA Fisheries
"""Write a markdown report from compare_seabed_methods.py output.

    python scripts/report_seabed_comparison.py --results <folder> --out <report.md>
"""

import argparse
import json
from pathlib import Path

import pandas as pd

COLUMNS = [
    ("seconds", "time (s)", "{:.1f}"),
    ("coverage", "coverage", "{:.2f}"),
    ("contrast_db", "contrast (dB)", "{:.1f}"),
    ("below_sv_db", "Sv below (dB)", "{:.1f}"),
    ("quiet_below_fraction", "quiet below", "{:.2f}"),
    ("jump_fraction", "jumps >10 m", "{:.2f}"),
    ("step_median_m", "step (m)", "{:.1f}"),
    ("consensus_mad_m", "vs consensus (m)", "{:.1f}"),
    ("consensus_within_5m", "within 5 m", "{:.2f}"),
]

METHOD_NOTES = {
    "bot": "echosounder's own .bot pick (EK60 only)",
    "evl": "analyst-edited Echoview line",
    "max_sv": "range-smoothed Sv maximum per ping, walked back 10 dB",
    "ep_basic": "echopype basic: first sample above -50 dB",
    "ep_blackwell": "echopype Blackwell, thresholds converted from electrical to physical degrees",
    "hdbscan": "experimental clustering detector on a range-coarsened window",
    "phase_m1": "phase-aware DP picker, Mode 1",
    "phase_m2": "phase-aware DP picker, Mode 2 (shape features)",
    "phase_m1_int": "Mode 1 backstepped integration line; sits above the echo by design",
    "phase_amp": "Mode 1 with angles withheld (amplitude-only)",
    "phase_m1_2nd": "Mode 1 on the secondary channel (18 kHz)",
    "phase_auto": "Mode 1 with no window given; the Mode 0 slab prior sets it",
}


def _fmt(value, fmt):
    try:
        if pd.isna(value):
            return ""
        return fmt.format(value)
    except (TypeError, ValueError):
        return str(value)


def _table(df):
    header = "| method | " + " | ".join(label for _, label, _ in COLUMNS) + " |"
    sep = "|---|" + "|".join("---:" for _ in COLUMNS) + "|"
    rows = [header, sep]
    for method, row in df.iterrows():
        cells = [_fmt(row.get(key), fmt) for key, _, fmt in COLUMNS]
        name = f"{method}*" if row.get("experimental") else method
        if isinstance(row.get("error"), str) and row["error"]:
            cells = [f"failed: {row['error'][:60]}"] + [""] * (len(COLUMNS) - 1)
        rows.append(f"| {name} | " + " | ".join(cells) + " |")
    return "\n".join(rows)


def _pairwise_table(pw):
    names = list(pw.index)
    rows = ["| | " + " | ".join(names) + " |", "|---|" + "|".join("---:" for _ in names) + "|"]
    for a in names:
        cells = []
        for b in names:
            v = pw.loc[a, b]
            cells.append("" if pd.isna(v) else (f"{v:.1f}" if names.index(a) > names.index(b) else f"{v:.2f}"))
        rows.append(f"| {a} | " + " | ".join(cells) + " |")
    return "\n".join(rows)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--findings", help="markdown file inserted after the introduction")
    args = parser.parse_args(argv)
    results = Path(args.results)
    out = Path(args.out)

    parts = [
        "# Seabed detection method comparison",
        "",
        "Generated by `AA-SI_Utils/scripts/compare_seabed_methods.py` and "
        "`report_seabed_comparison.py`. Every method ran on the same calibrated, "
        "surface-referenced Sv with split-beam angles, per raw file, on the search "
        "window listed for each dataset. None of the lines is ground truth, so the "
        "tables report speed, reference-free sanity checks and agreement.",
        "",
        "Columns: **time** is detector time only, summed over the dataset's files "
        "(Sv preparation is shared and excluded). **contrast** is the median over "
        "pings of mean Sv in the two pulse lengths below the line minus mean Sv 5 to "
        "10 m above it. **Sv below** is the median echo intensity just below the line. "
        "**quiet below** is the fraction of pings whose band below the line is under "
        "-60 dB, meaning the line is in water. **jumps** is the fraction of "
        "ping-to-ping changes over 10 m and **step** their median. **vs consensus** is "
        "the median absolute deviation from the per-ping median of one line per method "
        "family (the phase variants do not vote), and **within 5 m** the fraction of "
        "pings within 5 m of it. Methods marked * are experimental.",
        "",
        "Methods:",
        "",
    ]
    parts += [f"- `{k}`: {v}" for k, v in METHOD_NOTES.items()]
    parts.append("")
    if args.findings:
        parts += [Path(args.findings).read_text(encoding="utf-8"), ""]

    for ds_dir in sorted(p for p in results.iterdir() if p.is_dir()):
        meta_path = ds_dir / "dataset.json"
        metrics_path = ds_dir / "metrics.csv"
        if not meta_path.exists() or not metrics_path.exists():
            continue
        meta = json.loads(meta_path.read_text())
        df = pd.read_csv(metrics_path, index_col="method")
        parts += [
            f"## {meta['name']}",
            "",
            f"{meta['sonar_model']}, {meta['n_ping']} pings, files {', '.join(meta['files'])}. "
            f"Window {meta['r_min']:.0f} to {meta['r_max']:.0f} m, primary channel {meta['primary_khz']:.0f} kHz. "
            f"Sv preparation {meta['prepare_seconds']:.0f} s. {meta.get('notes', '')}",
            "",
            _table(df),
            "",
        ]
        pw_path = ds_dir / "pairwise.csv"
        if pw_path.exists():
            pw = pd.read_csv(pw_path, index_col=0)
            if len(pw):
                parts += [
                    "Pairwise agreement: median absolute difference in metres below the "
                    "diagonal, fraction of pings within 5 m above it.",
                    "",
                    _pairwise_table(pw),
                    "",
                ]
        if (ds_dir / "overlay.png").exists():
            rel = (ds_dir / "overlay.png").relative_to(out.parent) if out.parent in (ds_dir / "overlay.png").parents else ds_dir / "overlay.png"
            parts += [f"![{meta['name']} overlay]({rel.as_posix()})", ""]

    out.write_text("\n".join(parts), encoding="utf-8")
    print("wrote", out)


if __name__ == "__main__":
    main()
